### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by g-goulis** [MikeyMike7777/BUGroups#1]
# This is a test Issue
## Markdown is used here
![image](https://user-images.githubusercontent.com/35247613/197901635-b4e46d4e-6038-4e89-b91c-c71d60fc8585.png)

**Comment by bryce-r37** [comment]
No bug in listener. Resolving issue.

**Comment by bryce-r37** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test issue](https://trello.com/c/8RuAwa1d/53-test-issue)
