### ISSUE TITLE
2 digit course sections

### ISSUE THREAD

**Issue by carsyn1** [MikeyMike7777/BUGroups#10]
when adding a course to a student's list of currently enrolled courses, if the section is 2 digits it doesn't register and stores nothing in section

**Comment by bryce-r37** [comment]
can this be fixed by simply removing leading zeroes in the string input, and showing an error window if input is nothing but zeroes?

**Comment by bryce-r37** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Two Digit Course Sections](https://trello.com/c/0NCdGqp1/71-two-digit-course-sections)

**Comment by bryce-r37** [comment]
now doing input validation for all fields
