### ISSUE TITLE
classmates tab

### ISSUE THREAD

**Issue by carsyn1** [MikeyMike7777/BUGroups#13]
need to get classmates from the database when you click on a course in the drop down on the classmates tab

**Comment by bryce-r37** [comment]
this is now functional. users should not be able to see themselves as a classmate. we should also add an empty jlabel between each classmate text box, and maybe display email and phone number along with name, with the availability only being visible in the popup (not changing the popup at all, just the initial display).

**Comment by bryce-r37** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Classmates Tab Implementation](https://trello.com/c/zHZS0UYg/73-classmates-tab-implementation)
