### ISSUE TITLE
error handling with changing name and password in settings

### ISSUE THREAD

**Issue by carsyn1** [MikeyMike7777/BUGroups#15]
i can change my password and name to nothing-- we want to ensure the user inputs something for these fields

**Comment by bryce-r37** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Settings Error Handling](https://trello.com/c/mkEJmVMx/75-settings-error-handling)

**Comment by CarsonBuntin** [comment]
this is done!!
